const EXTRA_PROMPTS = [
  {
    "id": "p23",
    "category": "워크북",
    "icon": "✦",
    "title": "감성 꽃 포스터",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 1번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n아이보리색 수제 종이 배경 위에 구성된 감성 아트 포스터. 화면 한쪽에는 섬세한 흑백 연필 선화 스타일의 소녀를 배치하고, 옆에는 해바라기 또는 수국 한 송이를 실제 꽃처럼 사실적으로 크게 표현한다. 하단에는 작은 메모 종이와 베이지색 마스킹테이프를 넣고, 주변에는 작은 하트와 점 장식을 아주 절제되게 더한다. 전체 분위기는 따뜻하고 조용하며 감성적인 느낌. 상단에는 짧은 문구를 넣을 수 있는 빈 여백을 남긴다. 실사 꽃 + 흑백 선화 + 종이 콜라주 스타일, 4:5 세로 비율, 4K, 8K detail, soft natural light, no logo, no watermark\n\n[영상 프롬프트 · 한국어]\n아이보리색 종이 위에 감성 꽃 포스터가 살아 움직이는 듯한 장면. 흑백 선화의 소녀 옆에 해바라기 또는 수국이 놓여 있고, 꽃잎이 아주 살짝 흔들린다. 메모지는 종이결이 느껴지며, 작은 하트와 점 장식이 부드럽게 나타난다. 카메라는 천천히 줌 인하며 따뜻한 자연광이 은은하게 비친다. 차분하고 감성적인 분위기, 아날로그 종이 콜라주 느낌, 9:16 세로 영상, 약 5초, 부드러운 움직임, no text\n\n[Video Prompt · English]\nA poetic emotional flower poster coming to life on an ivory handmade paper background. A delicate black-and-white pencil sketch girl stands beside a realistic sunflower or hydrangea. The flower petals gently sway, the paper memo shows subtle texture, and tiny heart and dot decorations softly appear. Slow zoom in, warm natural light, calm and elegant mood, analog paper collage aesthetic, vertical 9:16 video, about 5 seconds, gentle motion, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p24",
    "category": "워크북",
    "icon": "✦",
    "title": "제주 바다 풍경",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 2번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n제주의 맑고 푸른 바다가 보이는 풍경. 에메랄드빛 바다와 하얀 포말, 맑은 하늘, 햇살이 비치는 제주 해안의 평화로운 장면. 화면 앞쪽에는 유채꽃 또는 풀꽃이 자연스럽게 배치되고, 전체 분위기는 따뜻하고 청량하며 감성적인 느낌으로 표현한다. 동화책 일러스트 스타일, 부드러운 자연광, 파스텔 톤, 섬세한 붓터치, 4:5 세로 비율, 4K, 8K detail, no text, no logo, no watermark\n\n[영상 프롬프트 · 한국어]\n제주의 푸른 바다와 하얀 파도가 부드럽게 움직이는 장면. 앞쪽에는 유채꽃과 풀꽃이 바람에 살짝 흔들리고, 햇살이 바다 위에 반짝인다. 카메라는 천천히 옆으로 이동하며 제주 해안의 평화롭고 청량한 분위기를 보여준다. 동화책 일러스트 스타일, 따뜻한 자연광, 감성적인 여행 영상 느낌, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA peaceful Jeju seaside scene with emerald ocean waves and soft white foam moving gently. In the foreground, canola flowers and wild grass sway lightly in the breeze, while sunlight sparkles on the water. The camera slowly pans sideways, revealing the calm and refreshing coastal mood of Jeju. Storybook illustration style, warm natural light, emotional travel video feeling, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p25",
    "category": "워크북",
    "icon": "✦",
    "title": "카페에서 책 읽는 여성",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 3번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n햇살이 비치는 조용한 카페 창가에 앉아 책을 읽는 20대 한국 여성. 테이블 위에는 커피 한 잔과 작은 꽃병이 놓여 있고, 창문으로 따뜻한 빛이 들어온다. 여성은 편안하고 차분한 표정이며, 전체 분위기는 잔잔하고 감성적이다. 부드러운 파스텔 색감의 동화책 일러스트 스타일, 아늑한 실내 분위기, 4:5 세로 비율, 4K, 8K detail, no text, no watermark\n\n[영상 프롬프트 · 한국어]\n햇살이 들어오는 카페 창가에서 20대 한국 여성이 책을 읽는 장면. 커피잔에서 은은한 김이 올라오고, 커튼이 아주 살짝 흔들린다. 여성이 페이지를 천천히 넘기며 조용히 미소 짓는다. 카메라는 천천히 앞으로 다가가며 아늑하고 따뜻한 카페 분위기를 담는다. 감성적인 동화풍 일러스트, 9:16 세로 영상, 약 5초, 부드러운 움직임, no text\n\n[Video Prompt · English]\nA cozy cafe scene with a Korean woman in her 20s reading a book by a sunlit window. Steam gently rises from a cup of coffee, and the curtain moves slightly in the breeze. She slowly turns a page and smiles softly. The camera slowly moves closer, capturing the warm and peaceful atmosphere. Emotional storybook illustration style, vertical 9:16 video, about 5 seconds, gentle motion, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p26",
    "category": "워크북",
    "icon": "✦",
    "title": "제주 감귤밭 산책",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 4번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n제주 감귤밭 사이를 천천히 걷는 20대 한국 여성. 감귤나무에는 주황빛 감귤이 자연스럽게 열려 있고, 여성이 손끝으로 감귤을 살짝 만지며 미소 짓고 있다. 따뜻한 햇살, 부드러운 바람, 편안하고 자연스러운 제주 여행 분위기. 감성적인 시네마틱 일러스트 스타일, 따뜻한 색감, 4:5 세로 비율, 4K, 8K detail, no text, no logo, no watermark\n\n[영상 프롬프트 · 한국어]\n제주 감귤밭 사이를 20대 한국 여성이 천천히 걷는 장면. 머리카락과 옷자락이 바람에 살짝 흔들리고, 손끝으로 감귤을 조심스럽게 만진다. 햇살이 감귤잎 사이로 부드럽게 비치고, 카메라는 여성의 움직임을 따라 천천히 이동한다. 따뜻하고 감성적인 제주 여행 영상 느낌, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA Korean woman in her 20s walks slowly through a Jeju tangerine orchard. Her hair and dress move gently in the breeze as she carefully touches a ripe tangerine with her fingertips. Warm sunlight filters through the leaves, and the camera slowly follows her movement. Soft, emotional Jeju travel mood, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p27",
    "category": "워크북",
    "icon": "✦",
    "title": "반려동물 캐릭터 일러스트",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 5번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n귀엽고 사랑스러운 말티즈 강아지를 주인공으로 한 캐릭터 일러스트. 큰 눈과 부드러운 털, 밝고 친근한 표정을 강조하고, 작은 스카프나 리본으로 포인트를 준다. 배경은 심플하게 하고, 전체 분위기는 따뜻하고 포근하며 동화책 같은 느낌으로 표현한다. 부드러운 색연필 일러스트 스타일, 4:5 세로 비율, 4K, 8K detail, no text, no watermark\n\n[영상 프롬프트 · 한국어]\n귀여운 말티즈 강아지가 화면 중앙에서 고개를 갸웃하고 꼬리를 살랑살랑 흔드는 장면. 귀와 털이 부드럽게 움직이고, 눈은 반짝이며 사랑스러운 표정을 짓는다. 배경은 심플하고 밝으며, 카메라는 천천히 줌 인한다. 따뜻하고 포근한 동화책 스타일, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA cute Maltese dog stands in the center, tilting its head and wagging its tail gently. Its ears and fluffy fur move softly, and its sparkling eyes create an adorable expression. The background is simple and bright, and the camera slowly zooms in. Warm and cozy storybook style, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p28",
    "category": "워크북",
    "icon": "✦",
    "title": "따뜻한 방 안의 정물화",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 6번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n따뜻한 오후 햇살이 들어오는 방 안의 감성적인 정물 장면. 나무 테이블 위에 책, 찻잔, 꽃병, 안경, 작은 메모지가 자연스럽게 놓여 있다. 부드러운 빛과 은은한 그림자가 감도는 조용한 분위기. 전체 색감은 아이보리, 베이지, 브라운, 라이트 그린 중심으로 따뜻하게 구성한다. 감성 일러스트 스타일 또는 수채화 스타일, 4:5 세로 비율, 4K, 8K detail, no text, no watermark\n\n[영상 프롬프트 · 한국어]\n따뜻한 오후 햇살이 들어오는 방 안의 정물 장면. 나무 테이블 위의 찻잔에서 가볍게 김이 올라오고, 꽃병 속 꽃이 아주 살짝 흔들린다. 창문에서 들어오는 빛이 천천히 움직이며 책과 안경 위에 부드러운 그림자를 만든다. 카메라는 테이블 위를 천천히 훑으며 감성적인 분위기를 보여준다. 9:16 세로 영상, 약 5초, 차분한 무드, no text\n\n[Video Prompt · English]\nA warm still-life scene inside a room filled with afternoon sunlight. Gentle steam rises from a teacup, and the flowers in a vase move slightly. Sunlight slowly shifts through the window, casting soft shadows over the book and glasses. The camera glides slowly across the table, capturing the peaceful and emotional atmosphere. Vertical 9:16 video, about 5 seconds, calm mood, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p29",
    "category": "워크북",
    "icon": "✦",
    "title": "밤하늘과 달빛 풍경",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 7번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n고요한 밤, 둥근 달이 떠 있는 하늘 아래 펼쳐진 감성 풍경. 잔잔한 호수 또는 바다 위로 달빛이 반사되고, 주변에는 억새나 나무 실루엣이 부드럽게 보인다. 전체 분위기는 몽환적이고 조용하며 시적인 느낌. 블루, 네이비, 실버, 라벤더 톤 중심의 감성 일러스트 스타일, 4:5 세로 비율, 4K, 8K detail, no text, no watermark\n\n[영상 프롬프트 · 한국어]\n둥근 달이 떠 있는 밤하늘과 달빛이 비치는 잔잔한 바다 또는 호수 풍경. 물결은 아주 부드럽게 흔들리고, 달빛은 반짝이며 길게 퍼진다. 억새나 나무 실루엣이 바람에 천천히 움직이고, 카메라는 천천히 앞으로 이동한다. 몽환적이고 시적인 분위기, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA dreamy night landscape with a full moon in the sky and moonlight reflecting on a calm sea or lake. The water ripples gently, and the moonlight sparkles across the surface. Silver grass or tree silhouettes sway softly in the breeze, while the camera slowly moves forward. Poetic and dreamy mood, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p30",
    "category": "워크북",
    "icon": "✦",
    "title": "동화책 속 아이와 작은 불빛",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 8번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n어두운 저녁, 작은 불빛을 손에 들고 길을 걷는 어린아이의 동화책 일러스트 장면. 아이는 따뜻한 표정으로 불빛을 바라보고 있으며, 주변에는 풀과 작은 꽃, 반짝이는 빛 입자가 부드럽게 떠다닌다. 전체 분위기는 포근하고 희망적이며 상상력이 느껴지는 동화 같은 장면. 수채화와 색연필이 섞인 부드러운 그림체, 4:5 세로 비율, 4K, 8K detail, no text, no logo, no watermark\n\n[영상 프롬프트 · 한국어]\n어두운 저녁길을 어린아이가 작은 불빛을 들고 천천히 걷는 장면. 불빛은 따뜻하게 반짝이고, 주변에는 작은 빛 입자들이 부드럽게 떠다닌다. 아이는 불빛을 바라보며 천천히 걸어가고, 풀과 꽃이 살짝 흔들린다. 카메라는 아이를 따라 부드럽게 이동한다. 포근하고 희망적인 동화풍 영상, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA child walks slowly along a dark evening path while holding a small glowing light. The light shines warmly, and tiny sparkling particles float softly in the air. The child looks at the light with a gentle expression, while grass and small flowers sway slightly. The camera follows the child smoothly. Cozy, hopeful storybook mood, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p31",
    "category": "워크북",
    "icon": "✦",
    "title": "여행 엽서 느낌의 풍경",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 9번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n여행 엽서처럼 보이는 감성 풍경 이미지. 화면에는 아름다운 제주 바다 또는 유채꽃밭 또는 숲길 또는 노을 풍경이 담겨 있고, 전체 구도는 심플하고 정돈되어 있다. 색감은 부드럽고 따뜻하며, 감성적인 여행 포스터 같은 무드로 표현한다. 깔끔한 여백과 세련된 구도, 감성 엽서 스타일, 4:5 세로 비율, 4K, 8K detail, no text, no logo, no watermark\n\n[영상 프롬프트 · 한국어]\n여행 엽서 속 풍경이 살아 움직이는 듯한 장면. 제주 바다 또는 유채꽃밭 또는 숲길이 부드럽게 움직이고, 바람에 꽃과 나뭇잎이 살짝 흔들린다. 햇살 또는 노을빛이 화면에 따뜻하게 번지며, 카메라는 천천히 줌 인한다. 감성적인 여행 포스터 분위기, 깔끔하고 세련된 영상, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA travel postcard-like landscape that comes alive. A Jeju seaside view, canola field, forest path, or sunset scene moves gently, with flowers and leaves swaying in the breeze. Warm sunlight or sunset glow spreads softly across the frame as the camera slowly zooms in. Emotional travel poster mood, clean and elegant style, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p32",
    "category": "워크북",
    "icon": "✦",
    "title": "나만의 창작 공간",
    "level": "초급",
    "ratio": "4:5 · 9:16",
    "tool": "이미지 AI · 영상 AI",
    "summary": "이미지와 영상 제작을 한 번에 연습하는 워크북 예제 10번입니다.",
    "when": "같은 주제로 이미지 한 장을 만든 뒤 자연스러운 움직임을 더한 영상까지 이어서 만들 때 사용합니다.",
    "prompt": "[이미지 프롬프트]\n따뜻하고 감성적인 창작 작업실 공간. 책상 위에는 노트북, 스케치북, 연필, 꽃, 커피잔, 작은 조명, 감성 소품들이 정돈되어 있다. 벽에는 그림이나 메모가 살짝 보이고, 창문으로는 부드러운 햇살이 들어온다. 전체 분위기는 아늑하고 창의적이며 작가의 작업실 같은 느낌. 감성 인테리어 일러스트 스타일, 따뜻한 베이지와 우드 톤 중심, 4:5 세로 비율, 4K, 8K detail, no text, no watermark\n\n[영상 프롬프트 · 한국어]\n따뜻한 햇살이 비치는 감성적인 창작 작업실. 책상 위의 커피잔에서 김이 오르고, 스케치북 페이지가 아주 살짝 넘어가며, 작은 조명이 은은하게 빛난다. 창문으로 들어오는 빛이 공간을 따뜻하게 비추고, 카메라는 책상 위를 천천히 훑으며 작가의 작업실 분위기를 보여준다. 아늑하고 창의적인 무드, 9:16 세로 영상, 약 5초, no text\n\n[Video Prompt · English]\nA warm and cozy creative studio filled with soft sunlight. Steam rises from a coffee cup, a sketchbook page gently lifts, and a small desk lamp glows softly. Light from the window warms the room as the camera slowly glides across the desk, revealing an artist’s inspiring workspace. Cozy and creative mood, vertical 9:16 video, about 5 seconds, no text.",
    "tip": "이미지를 먼저 만든 뒤 같은 주제의 영상 프롬프트를 적용하고, 색감·분위기·카메라를 하나씩 바꿔 비교하세요.",
    "variation": "주인공 / 장소 / 계절 / 카메라 움직임",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p33",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "나전칠기 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "검은 옻칠 바탕 위에 자개로 파도, 서핑보드, 햇빛을 표현하는 고급 전통 공예 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 푸른 바다에서 서핑을 즐기는 20대 한국 여성. 밝고 화사한 햇살 아래, 여성이 서핑보드 위에서 파도를 타며 자유롭고 신나는 표정을 짓고 있다. 에메랄드빛 바다와 제주 해안의 생동감이 느껴지는 장면. 전체 이미지는 한국 전통 나전칠기 스타일로 표현한다. 깊고 윤기 있는 검은 옻칠 바탕 위에 자개 조각으로 파도, 서핑보드, 햇빛, 물결을 정교하게 표현한다. 자개에는 청록, 사파이어 블루, 터쿼이즈, 진주빛 반사가 살아나고, 빛의 각도에 따라 오묘하게 반짝이도록 한다. 여성의 실루엣과 움직임도 자개 문양처럼 우아하고 세련되게 표현한다. 고급스럽고 화려한 전통 공예 작품 느낌, 정교한 수공예 디테일, 전시 작품 같은 완성도. 4:5 세로 비율, 4K, 8K detail, ultra detailed nacre inlay art, Korean lacquerware style, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 화사하고 신나는 분위기, 나전칠기 스타일, 자개 파도와 햇빛, 추천 색상: 청록, 사파이어 블루, 딥 네이비, 진주빛 화이트, 소프트 골드, 4:5 세로, no text",
    "tip": "추천 색상: 청록, 사파이어 블루, 딥 네이비, 진주빛 화이트, 소프트 골드",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p34",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "한지 콜라주 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "찢은 한지와 겹쳐 붙인 종이 질감으로 바다와 파도를 표현하는 한국적 감성의 종이 아트.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 밝은 바다에서 서핑하는 20대 한국 여성. 여성이 파도를 타며 즐겁고 생기 있는 표정을 짓고 있고, 푸른 바다와 햇빛, 제주 해안의 시원한 분위기가 함께 보인다. 전체 이미지는 한지 콜라주 스타일로 표현한다. 찢은 한지 조각을 여러 겹 겹쳐 붙여 바다, 파도, 하늘, 햇살을 구성하고, 종이의 섬유질과 결이 자연스럽게 보이게 한다. 파도는 청록, 하늘색, 아이보리 톤의 한지 레이어로 입체감 있게 만들고, 인물과 서핑보드도 한국적인 종이 공예 느낌으로 표현한다. 제주 감성이 느껴지는 따뜻하고 예술적인 분위기, 수공예 전시 작품 같은 감성. 4:5 세로 비율, 4K, 8K detail, Korean hanji collage art, layered paper texture, handmade fine art, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 밝고 경쾌한 분위기, 한지 콜라주 스타일, 찢은 종이 질감의 바다와 파도, 추천 색상: 아이보리, 스카이 블루, 청록, 베이지, 옅은 코랄, 4:5 세로, no text",
    "tip": "추천 색상: 아이보리, 스카이 블루, 청록, 베이지, 옅은 코랄",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p35",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "유리 모자이크 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "에메랄드·코발트·터쿼이즈 유리 조각으로 바다를 표현하는 화려하고 현대적인 스테인드글라스 감성.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장에서 서핑을 즐기는 20대 한국 여성. 햇빛이 바다 위에 반짝이고, 여성이 역동적으로 파도를 타며 밝고 자유로운 에너지를 보여준다. 바다는 청량하고 화사하며 여름의 활기가 느껴진다. 전체 이미지는 유리 모자이크 아트 스타일로 표현한다. 에메랄드, 코발트 블루, 터쿼이즈, 아쿠아 톤의 작은 유리 조각들로 바다와 파도를 구성하고, 햇빛은 스테인드글라스처럼 반짝이는 조각으로 표현한다. 여성과 서핑보드도 유리 조각이 이어진 형태로 세련되게 묘사하며, 빛을 받는 유리 표면의 투명감과 반사가 강조되게 한다. 현대적이고 화려하며 시각적으로 강렬한 아트워크. 4:5 세로 비율, 4K, 8K detail, stained glass mosaic style, luminous glass reflections, modern decorative art, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 화사한 여름 분위기, 유리 모자이크 스타일, 에메랄드와 코발트 바다, 추천 색상: 에메랄드, 코발트 블루, 터쿼이즈, 아쿠아, 투명 화이트, 4:5 세로, no text",
    "tip": "추천 색상: 에메랄드, 코발트 블루, 터쿼이즈, 아쿠아, 투명 화이트",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p36",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "페이퍼컷 아트 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "여러 겹의 종이를 층층이 쌓아 파도와 제주 해안을 입체적으로 표현하는 깔끔한 디자인 포스터 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 시원한 바다에서 서핑하는 20대 한국 여성. 환한 햇살, 파도, 제주 해안선이 밝고 경쾌한 분위기를 만들고, 여성은 서핑보드 위에서 신나고 자유로운 자세를 취하고 있다. 전체 이미지는 페이퍼컷 아트 스타일로 표현한다. 여러 겹의 종이를 층층이 쌓아 파도, 해안, 하늘, 햇빛을 입체적으로 구성한다. 바다는 코발트 블루와 터쿼이즈 종이 레이어로 단순하면서도 세련되게 표현하고, 인물과 서핑보드도 깔끔한 실루엣과 디자인적인 형태로 표현한다. 그림자는 종이 레이어의 깊이에서 자연스럽게 생기도록 하고, 전체적으로 포스터 같은 깔끔하고 감각적인 느낌을 준다. 4:5 세로 비율, 4K, 8K detail, layered papercut art, clean poster-like composition, dimensional paper art, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 밝고 깔끔한 분위기, 페이퍼컷 아트 스타일, 층층이 쌓인 입체 파도, 추천 색상: 코발트 블루, 터쿼이즈, 아이보리, 샌드 베이지, 코랄, 4:5 세로, no text",
    "tip": "추천 색상: 코발트 블루, 터쿼이즈, 아이보리, 샌드 베이지, 코랄",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p37",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "도자기 청화백자 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "순백의 도자기 바탕에 푸른 안료로 제주 바다와 서핑 장면을 문양처럼 표현하는 한국적 현대 아트.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성의 장면. 여성은 파도를 타며 밝고 유쾌한 표정을 짓고 있고, 제주 바다의 움직임과 시원한 햇살이 조화롭게 어우러진다. 전체 이미지는 한국 청화백자 스타일로 표현한다. 순백의 도자기 바탕 위에 푸른 안료로 파도, 서핑보드, 인물, 햇빛, 제주 해안을 문양처럼 섬세하게 그려 넣는다. 바다는 전통 도자기 문양의 흐름을 살리면서도 현대적인 감각으로 표현하고, 인물은 우아한 곡선과 간결한 붓선으로 정리한다. 전통과 현대가 결합된 세련된 한국 아트 느낌, 차분하면서도 독창적인 분위기. 4:5 세로 비율, 4K, 8K detail, blue-and-white porcelain style, elegant ceramic painting aesthetic, refined Korean modern art, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 시원하고 한국적인 분위기, 청화백자 스타일, 푸른 도자기 문양 같은 바다, 추천 색상: 순백, 코발트 블루, 인디고, 세룰리안 블루, 옅은 회청색, 4:5 세로, no text",
    "tip": "추천 색상: 순백, 코발트 블루, 인디고, 세룰리안 블루, 옅은 회청색",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p38",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "실크 자수 + 비즈 아트 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "실크 자수 위에 비즈·스팽글 같은 반짝임을 더해 바다와 햇살을 화려하게 표현하는 섬유 공예 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 햇살 가득한 바다 위에서 서핑하는 20대 한국 여성. 파도는 반짝이고, 여성은 밝고 경쾌한 표정으로 서핑을 즐기고 있다. 전체 분위기는 화사하고 신나며 여름 휴양지의 활기가 느껴진다. 전체 이미지는 화려한 실크 자수와 비즈 아트 스타일로 표현한다. 바다와 파도는 촘촘한 자수실과 다양한 스티치로 표현하고, 물방울과 햇빛은 비즈, 스팽글, 진주 장식처럼 반짝이게 한다. 여성의 의상과 머리카락, 서핑보드는 섬세한 자수로 표현하고, 바다 위에 빛나는 디테일을 풍성하게 살린다. 패션 일러스트와 공예 작품이 결합된 듯한 고급스럽고 화려한 전시 작품 느낌. 4:5 세로 비율, 4K, 8K detail, silk embroidery with beads and sequins, luxurious textile art, sparkling handcrafted detail, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 반짝이고 화려한 분위기, 실크 자수 + 비즈 아트 스타일, 추천 색상: 터쿼이즈, 아쿠아 블루, 진주빛 화이트, 실버, 샴페인 골드, 코랄 핑크, 4:5 세로, no text",
    "tip": "추천 색상: 터쿼이즈, 아쿠아 블루, 진주빛 화이트, 실버, 샴페인 골드, 코랄 핑크",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p39",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "구아슈 포스터 일러스트 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "색면을 단순하게 정리한 여행 포스터 스타일로, 선명하고 대중적인 홍보용 비주얼에 적합한 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성. 코발트 블루 바다와 밝은 햇살, 제주의 청량한 여름 분위기 속에서 여성이 서핑보드 위에 서서 역동적이고 즐거운 순간을 보여준다. 전체 이미지는 구아슈 포스터 일러스트 스타일로 표현한다. 색면을 단순하고 선명하게 정리하고, 코발트 블루, 코랄, 아이보리, 터쿼이즈 중심의 산뜻한 컬러 팔레트를 사용한다. 파도와 하늘은 그래픽적으로 깔끔하게 정리하고, 인물은 심플하지만 생동감 있게 표현한다. 여행 포스터 같은 세련된 감각, 홍보물과 SNS 썸네일에 잘 어울리는 선명하고 디자인적인 스타일. 4:5 세로 비율, 4K, 8K detail, gouache poster illustration, bold simplified shapes, travel poster aesthetic, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 밝고 경쾌한 분위기, 구아슈 포스터 일러스트 스타일, 여행 포스터 느낌, 추천 색상: 코발트 블루, 코랄, 아이보리, 선샤인 옐로우, 터쿼이즈, 4:5 세로, no text",
    "tip": "추천 색상: 코발트 블루, 코랄, 아이보리, 선샤인 옐로우, 터쿼이즈",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p40",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "3D 클레이 아트 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "점토로 만든 듯한 말랑한 입체 질감으로 파도와 인물을 표현하는 친근하고 귀여운 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 밝은 바다에서 서핑하는 20대 한국 여성. 파도와 바다, 햇빛이 귀엽고 경쾌하게 표현되고, 여성은 서핑보드 위에서 신나고 자유로운 자세를 취하고 있다. 전체 이미지는 3D 클레이 아트 스타일로 표현한다. 인물, 파도, 서핑보드, 햇빛을 모두 점토로 만든 듯한 말랑하고 입체적인 질감으로 표현한다. 바다는 터쿼이즈와 코발트 블루 클레이 레이어로 단순화하고, 여성의 표정은 밝고 친근하게 표현한다. 전체 분위기는 귀엽고 대중적이며, 강의 예시나 친근한 콘텐츠에 잘 어울리는 사랑스러운 입체 일러스트 느낌. 4:5 세로 비율, 4K, 8K detail, cute 3D clay art, playful and bright style, soft sculpted texture, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 귀엽고 밝은 분위기, 3D 클레이 아트 스타일, 말랑한 점토 질감, 추천 색상: 아쿠아 블루, 민트, 피치 코랄, 크림, 라이트 옐로우, 4:5 세로, no text",
    "tip": "추천 색상: 아쿠아 블루, 민트, 피치 코랄, 크림, 라이트 옐로우",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p41",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "수묵담채 현대화 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "먹선과 옅은 채색으로 파도를 표현하되 현대적인 컬러 포인트를 더한 차분한 동양화풍 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 바다에서 서핑하는 20대 한국 여성. 파도 위를 타는 역동적인 움직임과 제주 바다의 시원한 공간감이 느껴지고, 밝은 햇살 속에서 여성은 자유롭고 활기찬 분위기를 보여준다. 전체 이미지는 수묵담채 현대화 스타일로 표현한다. 먹선으로 파도의 흐름과 인물의 동세를 부드럽고 유려하게 잡고, 옅은 청색과 터쿼이즈, 코랄 포인트를 담채로 은은하게 더한다. 여백을 살리면서도 제주 바다의 움직임과 햇빛의 생기를 세련되게 담아낸다. 전통 동양화 감성과 현대적 컬러 감각이 결합된 차분하고 독특한 작품 느낌. 4:5 세로 비율, 4K, 8K detail, modern ink wash painting with light color, Korean contemporary art style, elegant brushwork, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 차분하고 독특한 분위기, 수묵담채 현대화 스타일, 먹선과 옅은 터쿼이즈 채색, 추천 색상: 먹색, 회청색, 터쿼이즈, 옅은 코랄, 미색, 4:5 세로, no text",
    "tip": "추천 색상: 먹색, 회청색, 터쿼이즈, 옅은 코랄, 미색",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p42",
    "category": "제주 스타일",
    "icon": "◫",
    "title": "나전 + 자수 혼합 스타일",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "파도와 바다는 자개, 인물과 의상은 자수로 표현하는 작품성 높은 혼합 미디어 스타일.",
    "when": "제주 중문해수욕장의 서핑 장면을 서로 다른 공예·회화 스타일로 비교 제작할 때 사용합니다.",
    "prompt": "[전체 프롬프트]\n제주 중문해수욕장의 눈부신 바다에서 서핑을 즐기는 20대 한국 여성. 에메랄드빛 파도와 햇살이 반짝이고, 여성은 서핑보드 위에서 생기 있고 자유로운 표정으로 서핑을 즐기고 있다. 밝고 화사하며 작품성이 높은 장면. 전체 이미지는 나전칠기와 자수 기법이 결합된 혼합 미디어 아트 스타일로 표현한다. 바다와 파도, 햇빛은 자개 조각으로 표현하여 청록, 사파이어, 진주빛 반사를 살리고, 여성의 의상과 인물 디테일, 서핑보드는 섬세한 자수로 표현한다. 자개의 반짝임과 자수의 부드러운 실결이 함께 어우러지며, 한국적이면서도 매우 독창적이고 고급스러운 전시 작품 느낌을 준다. 공모전, 전시, 대표작에 어울리는 높은 완성도의 아트 스타일. 4:5 세로 비율, 4K, 8K detail, mixed media nacre inlay and embroidery art, luxurious Korean contemporary craft style, highly artistic, no text, no logo, no watermark\n\n[짧은 한 줄 프롬프트]\n제주 중문해수욕장에서 서핑하는 20대 한국 여성, 작품성 높은 밝은 분위기, 나전 + 자수 혼합 스타일, 자개 바다와 자수 인물, 추천 색상: 청록, 사파이어 블루, 진주빛 화이트, 라벤더, 소프트 골드, 코랄, 4:5 세로, no text",
    "tip": "추천 색상: 청록, 사파이어 블루, 진주빛 화이트, 라벤더, 소프트 골드, 코랄",
    "variation": "서핑 → 해녀 / 중문 → 협재 / 여름 → 노을",
    "source": "AI 아트 프롬프트 워크북"
  },
  {
    "id": "p43",
    "category": "나전",
    "icon": "◈",
    "title": "LUMINOUS NACRE 긴 마스터",
    "level": "고급",
    "ratio": "4:5",
    "tool": "ChatGPT Image",
    "summary": "고요한 여백과 한 곳의 빛을 중심으로 자개의 물성을 정교하게 설계합니다.",
    "when": "한국 전통 나전칠기의 재료감과 현대적인 여백을 살린 작품을 만들 때 사용합니다.",
    "prompt": "[주제]를 한국 전통 나전칠기의 아름다움과 물성에서 영감을 받은 GIOMAR만의 현대적인 자개 예술 작품으로 재해석해 주세요.\n단순히 [주제]의 표면에 자개 질감을 입히거나 전통 장식으로 화면을 가득 채우지 않습니다. 먼저 [주제]가 가진 형태, 문화적 의미와 분위기에서 가장 중요한 이야기 또는 정서 하나를 찾아 작품의 중심 콘셉트로 설정합니다. 그 의미를 글자가 아니라 형태·패각·빛·어둠·여백의 흐름으로 전달합니다.\n[주제의 형태]\n[주제]의 고유한 실루엣과 핵심 특징은 한눈에 알아볼 수 있도록 온전하게 유지합니다. 주제가 깨지거나 부서지거나 일부가 손상된 모습으로 표현하지 않습니다. 어둠과 만나는 부분에서도 형태 자체가 없어지는 것이 아니라 표면을 이루는 자개의 밀도와 반사광만 점차 약해져 흑칠 속으로 스며들게 합니다.\n“형상이 사라지는 것이 아니라, 형상을 덮고 있는 빛이 사라집니다.”\n[자개의 물성]\n자개는 보석·크리스털·홀로그램·글리터가 아니라 실제 얇은 패각을 장인이 손으로 잘라 하나씩 이어 붙인 것처럼 표현합니다. 가늘고 긴 패각, 불규칙한 작은 조각, 아주 미세한 패각을 자연스럽게 혼합합니다. 미세한 절단면과 이어 붙인 흔적이 느껴져야 하며 동일한 크기의 둥근 조각이 반복되는 디지털 모자이크처럼 표현하지 않습니다. 패각의 방향과 배열은 [주제]의 윤곽·곡선·움직임을 따라 자연스럽게 흐르도록 합니다.\n[GIOMAR 자개 컬러]\n기본 색은 진주빛과 은백색입니다. 빛의 각도에 따라 청록빛·공작석빛 블루·깊은 남보라·진주빛이 자연스럽고 미묘하게 변화하는 실제 자개의 간섭광을 표현합니다. 밝은 패각, 은은한 패각, 거의 빛나지 않는 패각을 함께 사용합니다. 금빛은 아주 미세한 세공선이나 포인트에만 제한적으로 사용합니다.\n[흑칠과 여백]\n배경은 깊고 매끄러운 한국 전통 검은 옻칠을 연상시키는 표면으로 표현합니다. 화면의 약 40~50%를 의도적인 어둠과 여백으로 남기고, 빈 공간을 꽃·별·구름·금가루·전통 문양으로 임의로 채우지 않습니다. 어둠 역시 작품을 구성하는 재료입니다.\n[한국적 상징]\n[주제]의 의미와 가장 깊게 연결되는 한국적 자연 또는 문화적 상징 하나만 선택합니다. 달, 산, 소나무, 파도, 구름, 꽃 등의 요소 가운데 이야기상 가장 적합한 하나를 사용합니다. 상징은 주제보다 크거나 밝지 않게 하고 일부만 희미하게 드러나거나 흑칠 속으로 스며들게 합니다.\n[빛의 연출]\n작품에서 가장 밝은 지점은 한 곳만 설정합니다. 한 방향에서 들어오는 부드럽고 절제된 빛이 [주제]의 가장 중요한 부분과 만나 패각의 자연스러운 간섭광을 드러냅니다. 빛은 선명한 자개 → 절제된 반사 → 작은 패각 → 희미한 빛의 흔적 → 깊은 흑칠 순서로 조용하게 사라집니다. 큰 패각이 공중으로 날아가거나 폭발하는 파편 효과는 사용하지 않습니다.\n[구도]\n완벽한 중앙 배치와 좌우대칭을 피합니다. 주제를 화면 한쪽으로 약간 이동시키고 반대편에는 충분한 여백을 확보합니다. 시선이 빛 → 주제 → 하나의 상징 → 여백 순으로 이동하도록 구성합니다.\n[최종 미학]\n화려함보다 깊이. 장식보다 이야기. 색보다 빛. 복잡함보다 여백. 파편보다 흐름. 복제보다 재해석.\nContemporary Korean nacre art, GIOMAR luminous nacre aesthetic, authentic handcrafted mother-of-pearl materiality, irregular hand-cut shell fragments, intact recognizable silhouette, deep Korean black lacquer, restrained pearl white, turquoise, peacock blue and deep violet natural iridescence, minimal gold accents, single-source poetic illumination, sophisticated negative space, asymmetrical Korean composition, tactile craftsmanship, quiet visual tension, contemporary museum-quality Korean art.\n피해야 할 요소: 디지털 모자이크, 동일한 크기의 반복 패턴, 화면 전체를 덮는 자개, 과도한 금색, 보석·크리스털, 홀로그램, 글리터, 네온, 크롬, 플라스틱 표면, 강한 무지갯빛, 깨진 주제, 큰 패각이 날아가는 모습, 폭발하는 파편, 과도한 균열, 여러 개의 장식적 상징, 의미 없이 추가된 꽃·나비·구름, 반복적인 전통 문양, 완벽한 좌우대칭, 서양식 바로크 장식, AI가 여백을 임의의 장식으로 채우는 구성.\n이미지 안에는 글자·로고·서명·워터마크를 넣지 않습니다.",
    "tip": "LUMINOUS는 여백과 한 개의 상징, SPLENDOR는 2~3개의 상징과 높은 자개 밀도에 적합합니다.",
    "variation": "달항아리 / 오름 / 학 / 모란 / 봉황 / 책가도",
    "source": "LUMINOUS NACRE 프롬프트 가이드"
  },
  {
    "id": "p44",
    "category": "나전",
    "icon": "◈",
    "title": "LUMINOUS NACRE 간단 버전",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image",
    "summary": "절제된 현대 나전 아트를 빠르게 생성하는 간단 버전입니다.",
    "when": "한국 전통 나전칠기의 재료감과 현대적인 여백을 살린 작품을 만들 때 사용합니다.",
    "prompt": "[주제]를 한국 전통 나전칠기의 물성에서 영감을 받은 GIOMAR 현대 자개 예술 작품으로 재해석해 주세요.\n깊고 매끄러운 검은 옻칠 배경 위에 [주제]의 고유한 실루엣을 온전하게 유지하고, 실제 장인이 손으로 잘라 이어 붙인 듯한 얇고 불규칙한 자개 패각으로 형상을 표현합니다.\n자개는 진주빛을 중심으로 빛의 각도에 따라 청록·공작석빛 블루·깊은 남보라·은백색이 미묘하게 변화하는 자연스러운 간섭광을 표현하고, 금빛은 아주 적은 세공 포인트에만 사용합니다.\n[주제]와 연결되는 한국적 상징 하나만 절제하여 배치하고, 화면의 40~50%는 깊은 흑칠과 여백으로 남깁니다.\n가장 밝은 지점은 한 곳만 두고, 선명한 자개 → 작은 패각 → 희미한 반사광 → 깊은 어둠으로 빛이 자연스럽게 사라지게 합니다. 형상은 깨지거나 파편으로 흩어지지 않습니다.\n화려함보다 깊이, 장식보다 이야기, 색보다 빛, 복잡함보다 여백.\nContemporary Korean nacre art, GIOMAR luminous nacre aesthetic, authentic handcrafted mother-of-pearl, irregular hand-cut shell fragments, deep black lacquer, restrained pearl, turquoise, peacock blue and deep violet iridescence, minimal gold, single poetic light source, sophisticated negative space, asymmetrical Korean composition, museum-quality contemporary Korean art.\n피하기: 디지털 모자이크, 과도한 금색, 글리터, 홀로그램, 크리스털, 강한 무지갯빛, 깨짐, 날아가는 큰 파편, 반복 문양, 과도한 장식, 플라스틱·크롬 표면.\n글자·로고·워터마크 없음. 4:5 세로, 고해상도.",
    "tip": "LUMINOUS는 여백과 한 개의 상징, SPLENDOR는 2~3개의 상징과 높은 자개 밀도에 적합합니다.",
    "variation": "달항아리 / 오름 / 학 / 모란 / 봉황 / 책가도",
    "source": "LUMINOUS NACRE 프롬프트 가이드"
  },
  {
    "id": "p45",
    "category": "나전",
    "icon": "◈",
    "title": "LUMINOUS NACRE SPLENDOR 마스터",
    "level": "고급",
    "ratio": "4:5",
    "tool": "ChatGPT Image",
    "summary": "풍성함과 장엄함을 강조하는 화려한 현대 나전 마스터 프롬프트입니다.",
    "when": "한국 전통 나전칠기의 재료감과 현대적인 여백을 살린 작품을 만들 때 사용합니다.",
    "prompt": "화려한 버전 · 풍성함과 장엄함을 강조하는 마스터 프롬프트\n이미지 예시 · 제주 오름을 화려한 나전칠기 미학으로 재해석한 SPLENDOR 방향\n[주제]를 한국 전통 나전칠기의 화려하고 정교한 공예미에서 영감을 받은 GIOMAR 현대 자개 예술 작품으로 재해석해 주세요.\n단순히 [주제]의 표면에 자개 질감을 입히는 것이 아니라, 수많은 크기와 형태의 실제 패각 조각이 서로 연결되어 하나의 장엄한 장면을 만들어내는 작품으로 표현합니다.\n[중심 주제]\n[주제]의 고유한 실루엣과 핵심 특징을 한눈에 알아볼 수 있도록 온전하게 유지합니다. 중요한 윤곽과 중심부에는 자개의 밀도를 높이고 주변으로 갈수록 세공의 밀도와 빛을 자연스럽게 변화시킵니다. 주제를 깨뜨리거나 파편화하지 않습니다.\n[화려하고 정교한 자개 세공]\n실제 한국 나전 공예처럼 얇고 불규칙하게 손으로 자른 패각 조각, 가느다란 자개 선, 미세한 절단면과 이어 붙인 흔적을 정교하게 표현합니다. 큰 패각과 작은 패각, 가느다란 선형 자개를 다양하게 혼합하고, 패각 배열은 [주제]의 형태·곡선·방향·움직임을 따라 유기적으로 흐르게 합니다.\n[GIOMAR SPLENDOR 컬러]\n깊은 검은 옻칠 위에서 진주빛 백색·은빛·청록·공작석빛 블루·사파이어 블루·깊은 남보라·자홍빛이 풍부하게 교차하도록 표현합니다. 금빛은 넓은 면을 칠하지 않고 가느다란 금빛 세공선, 윤곽선, 작은 연결 장식과 포인트로 사용합니다.\n[깊은 흑칠]\n배경은 깊고 윤택한 검은 옻칠 표면입니다. 여러 겹의 옻칠이 쌓인 듯한 깊이와 미세한 반사, 매끄러운 광택을 살려 어둠 속에서 수천 개의 자개가 빛나는 듯한 대비를 만듭니다.\n[풍성한 한국적 장식]\n[주제]와 어울리는 한국적 자연·문화 요소 중 2~3개를 선택합니다. 예: 달 / 구름 / 모란 / 매화 / 소나무 / 파도 / 바위 / 산 / 학 / 나비 / 전통 문양. 장식은 단순한 채우기가 아니라 중심 주제와 연결되는 장면이 되도록 하며 전경·중경·후경의 깊이를 만듭니다.\n[빛]\n하나의 강한 주광을 중심으로 주변 자개에 풍부한 반사광이 이어지도록 합니다. 주광을 받은 패각은 진주 → 청록 → 블루 → 보라 → 은빛으로 변화하고 일부에는 매우 미세한 분홍·금빛 간섭광이 나타납니다. 자개 자체가 네온처럼 발광하지 않고 실제 패각이 빛을 반사하는 광택으로 표현합니다.\n[구도]\n중심 주제가 가장 먼저 보이고 주변 자연 요소가 겹겹이 이어지는 풍성하고 장엄한 구성을 만듭니다. 자개 밀도를 높이되 화면 전체를 동일한 밀도로 채우지 않습니다. 시각적 강약은 주제 100 → 주변 상징 70 → 장식 40 → 흑칠 20 정도로 설정합니다.\n[최종 미학]\n화려하지만 값싸게 번쩍이지 않게. 풍성하지만 혼란스럽지 않게. 전통적이지만 고루하지 않게. 장식적이지만 중심 이야기를 잃지 않게.\nOpulent contemporary Korean nacre art, GIOMAR Luminous Nacre Splendor aesthetic, authentic Korean mother-of-pearl inlay craftsmanship, luxurious deep black lacquer, densely layered hand-cut shell fragments, intricate shell linework, luminous natural nacre interference, pearl white, turquoise, peacock blue, sapphire, deep violet and subtle magenta reflections, elegant fine gold inlay accents, richly layered Korean natural motifs, dramatic reflected illumination, exquisite handcrafted materiality, sophisticated ornamental composition, luxurious yet refined, museum-quality Korean decorative art, extraordinary craftsmanship, highly detailed.\n반드시 피하기: 디지털 모자이크, 욕실 타일 같은 패턴, 동일한 크기의 패각 반복, 싸구려 글리터, 홀로그램 필름, 네온 발광, 크리스털·보석으로 변한 자개, 과도한 노란 금색, 플라스틱·크롬 표면, 깨진 주제, 폭발하는 패각, 공중에 날아다니는 큰 파편, 서양 바로크 장식, 중국풍 요소의 무분별한 혼합, 의미 없는 장식의 과잉, 중심 주제가 묻히는 복잡한 구성.\n이미지 안에는 글자·로고·서명·워터마크를 넣지 않습니다.",
    "tip": "LUMINOUS는 여백과 한 개의 상징, SPLENDOR는 2~3개의 상징과 높은 자개 밀도에 적합합니다.",
    "variation": "달항아리 / 오름 / 학 / 모란 / 봉황 / 책가도",
    "source": "LUMINOUS NACRE 프롬프트 가이드"
  },
  {
    "id": "p46",
    "category": "나전",
    "icon": "◈",
    "title": "SPLENDOR 수강생용 간단 버전",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image",
    "summary": "화려하지만 중심이 분명한 현대 나전 작품을 만드는 간단 버전입니다.",
    "when": "한국 전통 나전칠기의 재료감과 현대적인 여백을 살린 작품을 만들 때 사용합니다.",
    "prompt": "[주제]를 화려하고 품격 있는 GIOMAR 현대 나전칠기 예술 작품으로 재해석해 주세요. 깊고 윤택한 검은 옻칠 위에 실제 장인이 손으로 자르고 이어 붙인 듯한 크고 작은 자개 패각과 가느다란 자개 선으로 [주제]의 온전한 형태를 표현합니다.\n자개는 진주빛·청록·공작석 블루·사파이어 블루·남보라·은빛·미세한 자홍빛이 빛의 각도에 따라 변화하는 천연 패각의 풍부한 간섭광을 보여줍니다. 가느다란 금빛 세공선을 포인트로 사용합니다.\n[주제]와 어울리는 한국적 자연·문화 요소 2~3개를 선택하여 전경·중경·후경에 풍성하게 구성하고, 흑칠의 깊은 어둠과 영롱한 자개의 강한 대비를 만듭니다.\n화려하지만 고급스럽게, 풍성하지만 중심이 분명하게, 실제 한국 나전칠기의 수공예 물성이 느껴지는 박물관급 현대 예술 작품.\nOpulent contemporary Korean nacre art, authentic mother-of-pearl inlay craftsmanship, deep glossy black lacquer, richly layered irregular hand-cut shell fragments, pearl, turquoise, peacock blue, sapphire, deep violet and silver natural iridescence, fine gold inlay accents, sophisticated Korean ornamental composition, luxurious handcrafted materiality, museum-quality artwork, highly detailed.\n피하기: 디지털 모자이크, 글리터, 홀로그램, 네온, 크리스털, 플라스틱, 과도한 노란 금색, 동일한 패각 반복, 깨짐·폭발·큰 파편, 값싼 장식 효과.\n글자·로고·워터마크 없음. 4:5 세로, 고해상도.",
    "tip": "LUMINOUS는 여백과 한 개의 상징, SPLENDOR는 2~3개의 상징과 높은 자개 밀도에 적합합니다.",
    "variation": "달항아리 / 오름 / 학 / 모란 / 봉황 / 책가도",
    "source": "LUMINOUS NACRE 프롬프트 가이드"
  },
  {
    "id": "p47",
    "category": "자기발견",
    "icon": "◎",
    "title": "AI가 발견한 나의 타입",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT",
    "summary": "대화에서 반복적으로 드러난 성향과 창작 세계를 한 장의 작품으로 번역합니다.",
    "when": "자신의 성향·색·상징·창작 세계를 분석하고 시각 작품으로 표현하고 싶을 때 사용합니다.",
    "prompt": "GIOMAR AI SELF-DISCOVERY ART 01\n「AI가 발견한 나의 타입은?」\n지금까지 사용자와 실제로 나눈 대화를 분석하여 이 사람만의 타입을 발견해 주세요.\n기존 MBTI나 정해진 성격 유형에 끼워 맞추지 않습니다.\n말투, 반복되는 관심사, 선택 기준, 일하는 방식, 창작 방식, 배우는 태도, 중요하게 생각하는 가치 등을 종합적으로 분석합니다.\n한두 번 등장한 내용보다 여러 대화에서 반복적으로 드러난 특징을 우선하고, 근거가 부족한 성향은 추측하지 않습니다.\n[먼저 내부적으로 분석할 것]\n• 가장 강하게 드러나는 성향 3가지\n• 이 사람이 무언가를 선택하는 기준\n• 일을 시작하고 완성하는 방식\n• 다른 사람과 구별되는 강점\n• 이 사람이 가장 자기다워지는 순간\n분석은 충분히 깊게 하되 이미지에 분석 내용을 모두 적지 않습니다.\n[최종 결과]\nMY TYPE: 사용자만의 독창적인 타입 이름\nONE LINE: “나는 ______하는 사람.”\n3 KEYWORDS: 사용자를 가장 잘 보여주는 단어 3개\n[VISUAL STYLE]\nContemporary Emotional Editorial\n독립 예술잡지의 인물 특집 페이지처럼 세련되고 감성적으로 표현합니다.\n다꾸, 스크랩북, 찢어진 메모지, 마스킹테이프, 종이클립, 여러 개의 정보 박스를 사용하지 않습니다.\n넓은 여백과 과감한 타이포그래피를 활용하고 사용자를 상징하는 하나의 인물, 오브제 또는 장면을 메인 비주얼로 선택합니다.\n사용자의 성향은 설명문보다 자세, 시선, 오브제, 빛과 공간으로 보여줍니다.\n컬러 역시 고정하지 말고 실제 대화를 분석해 사용자에게 맞는 색을 결정합니다.\n고급 독립 아트 매거진의 표지와 에디토리얼 아트가 결합된 느낌으로 표현합니다.\n[IMAGE TEXT]\n나의 타입은?\n[TYPE NAME]\n나는 ______하는 사람.\nKEYWORD 1 · KEYWORD 2 · KEYWORD 3\n다른 설명은 넣지 않습니다. 화면의 최소 75%는 이미지와 여백으로 사용합니다.\n핵심: AI는 많이 분석하고, 작품은 적게 말합니다. 사용자가 결과를 보고 “정말 나 같은데?”라고 느끼게 해주세요.",
    "tip": "충분한 대화 기록이 있는 채팅에서 사용해야 결과가 더 구체적이며, 확인되지 않은 성향은 추측하지 않도록 합니다.",
    "variation": "타입 / 창작 컬러 / 동물 / 마음의 정원 / 작가 캐릭터",
    "source": "AI SELF-DISCOVERY ART 01–05"
  },
  {
    "id": "p48",
    "category": "자기발견",
    "icon": "◎",
    "title": "AI가 발견한 나의 창작 컬러",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT",
    "summary": "대화에서 반복적으로 드러난 성향과 창작 세계를 한 장의 작품으로 번역합니다.",
    "when": "자신의 성향·색·상징·창작 세계를 분석하고 시각 작품으로 표현하고 싶을 때 사용합니다.",
    "prompt": "GIOMAR AI SELF-DISCOVERY ART 02\n「AI가 발견한 나의 창작 컬러는?」\n지금까지 사용자와 실제로 나눈 대화를 분석하여 이 사람의 성향과 창작 세계를 색으로 번역해 주세요.\n사용자가 단순히 좋아한다고 말한 색을 선택하거나 일반적인 색채심리 공식에 대입하지 않습니다.\n말투, 감성, 관심사, 창작 방식, 중요하게 생각하는 가치, 반복적으로 선택하는 분위기를 종합적으로 분석합니다.\n[내부 분석]\n사용자를 이루는 감성 DNA 4가지를 찾습니다.\nMAIN COLOR 1개: 사용자의 중심적인 성향\nSUPPORTING COLORS 2개: 사용자의 서로 다른 면\nSIGNATURE COLOR 1개: 이 사람만의 개성을 보여주는 색\n각 색에는 평범한 색 이름 대신 사용자의 이야기를 담은 감성적인 이름을 붙입니다.\n[VISUAL STYLE]\nEmotional Abstract Color Portrait\n사용자를 인물로 그리지 않습니다.\n그 사람의 감정, 생각, 에너지와 창작 세계를 색·빛·질감·형태로 만든 추상 자화상으로 표현합니다.\n다꾸, 종이 메모, 캐릭터, 정보 카드, 컬러 설명표, 인포그래픽을 사용하지 않습니다.\n화면 전체가 하나의 대형 현대 추상회화처럼 보여야 합니다.\n반투명한 컬러 레이어, 깊이 있는 안료, 부드러운 빛, 색이 서로 스며드는 경계, 미세한 질감과 흔적을 활용합니다.\n색상들이 동일한 면적으로 나뉘지 않고 사용자의 중심 성향에 따라 자연스럽게 흐르고 겹쳐지도록 합니다.\n갤러리에 전시된 현대 추상미술 작품처럼 표현합니다.\n[IMAGE TEXT]\n나의 창작 컬러는?\n[MAIN COLOR의 감성 이름]\n“나를 색으로 번역하다.”\n이 세 요소 외에는 텍스트를 넣지 않습니다.\n핵심: 색을 설명하지 마세요. 색 자체가 그 사람을 이야기하게 해주세요.",
    "tip": "충분한 대화 기록이 있는 채팅에서 사용해야 결과가 더 구체적이며, 확인되지 않은 성향은 추측하지 않도록 합니다.",
    "variation": "타입 / 창작 컬러 / 동물 / 마음의 정원 / 작가 캐릭터",
    "source": "AI SELF-DISCOVERY ART 01–05"
  },
  {
    "id": "p49",
    "category": "자기발견",
    "icon": "◎",
    "title": "AI가 발견한 나를 닮은 동물",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT",
    "summary": "대화에서 반복적으로 드러난 성향과 창작 세계를 한 장의 작품으로 번역합니다.",
    "when": "자신의 성향·색·상징·창작 세계를 분석하고 시각 작품으로 표현하고 싶을 때 사용합니다.",
    "prompt": "GIOMAR AI SELF-DISCOVERY ART 03\n「AI가 발견한 나를 닮은 동물은?」\n지금까지 사용자와 실제로 나눈 대화를 분석하여 이 사람의 행동과 삶의 방식에 가장 가까운 동물을 발견해 주세요.\n귀여움이나 외모로 결정하지 않습니다.\n[내부 분석]\n실제 대화에서 반복적으로 드러난 핵심 성향 3가지를 찾습니다.\n그 후 최소 7종 이상의 서로 다른 동물을 내부적으로 비교하고 가장 적합한 동물 하나를 선택합니다.\n동물에 대한 과장된 성격 고정관념보다는 실제 행동적 특성과 문화적 상징성을 참고합니다.\n선택한 동물과 사용자의 연결 이유는 내부적으로 분석하되 이미지 안에 장문의 설명을 넣지 않습니다.\n[VISUAL STORYTELLING]\n선택한 동물이 사용자의 성향을 보여주는 한 가지 행동을 하도록 합니다.\n탐구하는 사람이라면 발견하는 장면, 만드는 사람이라면 창작하는 장면, 사람을 연결하는 사람이라면 함께하는 장면처럼 가장 강한 특징을 행동으로 보여주세요.\n사용자의 실제 관심사를 상징하는 오브제 2~3개를 장면 안에 자연스럽게 숨겨놓습니다.\n[VISUAL STYLE]\nCinematic Hand-Painted Storybook\n다꾸 포스터나 캐릭터 프로필 카드로 만들지 않습니다.\n찢어진 종이, 마스킹테이프, 설명 박스, 체크리스트를 사용하지 않습니다.\n한 권의 아름다운 그림책을 펼쳤을 때 만나는 한 장면처럼 표현합니다.\n회화적인 붓 터치, 섬세한 색연필 선, 자연스러운 빛과 그림자, 깊이 있는 배경, 영화적인 화면 구도를 사용합니다.\n캐릭터 상품처럼 지나치게 귀엽게 만들지 않습니다.\n동물 본래의 특징을 살리면서 따뜻하고 시적인 분위기를 표현합니다.\n[IMAGE TEXT]\n나를 닮은 동물은?\n[동물 이름]\n“당신을 닮은 이유를 이 장면 안에 담았습니다.”\n그 외 설명은 넣지 않습니다.\n핵심: 왜 이 동물인지 글로 설명하기보다 그림을 보면 느껴지게 해주세요.",
    "tip": "충분한 대화 기록이 있는 채팅에서 사용해야 결과가 더 구체적이며, 확인되지 않은 성향은 추측하지 않도록 합니다.",
    "variation": "타입 / 창작 컬러 / 동물 / 마음의 정원 / 작가 캐릭터",
    "source": "AI SELF-DISCOVERY ART 01–05"
  },
  {
    "id": "p50",
    "category": "자기발견",
    "icon": "◎",
    "title": "AI가 그린 내 마음의 정원",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT",
    "summary": "대화에서 반복적으로 드러난 성향과 창작 세계를 한 장의 작품으로 번역합니다.",
    "when": "자신의 성향·색·상징·창작 세계를 분석하고 시각 작품으로 표현하고 싶을 때 사용합니다.",
    "prompt": "GIOMAR AI SELF-DISCOVERY ART 04\n「AI가 그린 내 마음의 정원은?」\n지금까지 사용자와 실제로 나눈 대화를 분석하여 이 사람의 가치, 관심사, 창작의 원천과 성장 방향을 하나의 상징적인 정원으로 만들어 주세요.\n이 작업은 심리검사나 정신상태 분석이 아닙니다.\n“이 사람의 이야기로 작은 세계를 만든다면 어떤 곳일까?”를 시각화하는 작업입니다.\n[내부 분석]\n• 소중하게 생각하는 것\n• 좋아하는 것\n• 창작의 원천\n• 지금 키우고 있는 것\n• 앞으로 향하고 싶은 방향\n각각을 식물, 길, 건물, 물, 빛, 문, 계단, 작업 공간 등 시각적인 상징으로 변환합니다.\n상징에는 반드시 실제 대화와 연결되는 이유가 있어야 합니다.\n[GARDEN NAME]\n분석 결과를 바탕으로 세상에 하나뿐인 정원 이름을 만듭니다.\n그리고 정원을 표현하는 한 문장을 작성합니다.\n[VISUAL STYLE]\nHandcrafted Miniature Dream World\n실제 사람이 손으로 만든 정교한 미니어처 디오라마를 매크로 카메라로 촬영한 것처럼 표현합니다.\n작은 나무, 미니어처 건축물, 돌길, 실제 같은 작은 식물, 조그마한 작업실, 작은 조명, 물과 유리, 수공예 흔적 등을 활용합니다.\n빛이 매우 중요합니다. 사용자의 분위기에 맞춰 새벽, 아침, 노을, 밤 중 가장 적합한 시간대를 선택합니다.\n얕은 심도와 미세한 빛망울을 활용하여 실제 미니어처 사진 같은 공간감을 만듭니다.\n다꾸, 인포그래픽, 설명 카드, 메모지는 사용하지 않습니다.\n[HIDDEN STORY]\n정원 안에는 사용자와의 실제 대화에서 발견한 상징 3~5개를 작은 이스터에그처럼 숨깁니다.\n처음 보면 아름다운 미니어처 세계이고, 자세히 보면 그 사람의 이야기가 발견되어야 합니다.\n[IMAGE TEXT]\n내 마음의 정원\n[정원의 이름]\n“이곳은 ______이 자라는 곳입니다.”\n그 외 텍스트는 넣지 않습니다.\n핵심: 설명하는 정원이 아니라 들어가 보고 싶은 나만의 작은 세계를 만들어 주세요.",
    "tip": "충분한 대화 기록이 있는 채팅에서 사용해야 결과가 더 구체적이며, 확인되지 않은 성향은 추측하지 않도록 합니다.",
    "variation": "타입 / 창작 컬러 / 동물 / 마음의 정원 / 작가 캐릭터",
    "source": "AI SELF-DISCOVERY ART 01–05"
  },
  {
    "id": "p51",
    "category": "자기발견",
    "icon": "◎",
    "title": "AI가 발견한 나의 작가 캐릭터",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT",
    "summary": "대화에서 반복적으로 드러난 성향과 창작 세계를 한 장의 작품으로 번역합니다.",
    "when": "자신의 성향·색·상징·창작 세계를 분석하고 시각 작품으로 표현하고 싶을 때 사용합니다.",
    "prompt": "GIOMAR AI SELF-DISCOVERY ART 05\n「AI가 발견한 나의 작가 캐릭터는?」\n지금까지 사용자와 실제로 나눈 대화를 분석하여\n“이 사람이 하나의 작가 페르소나가 된다면 어떤 모습일까?”를 시각화해 주세요.\n단순한 프로필 캐릭터나 예쁜 AI 아바타를 만들지 않습니다.\n사용자의 창작 방식, 관심사, 가치관, 강점과 앞으로 확장할 수 있는 방향을 하나의 상징적인 작가 캐릭터에 담습니다.\n[STEP 1. CREATIVE DNA]\n실제 대화를 바탕으로 사용자의 창작 DNA 5가지를 찾습니다.\n각 키워드는 서로 다른 특징을 보여줘야 합니다.\n[STEP 2. ARTIST PERSONA]\nARTIST NAME: 사용자의 작가적 성향을 표현하는 이름\nCREATIVE TYPE: 어떤 창작자인지 한 문장\nCREATIVE DNA: 핵심 키워드 3개\nSIGNATURE OBJECT: 사용자를 상징하는 오브제 하나\nSIGNATURE SYMBOL: 창작 세계를 상징하는 형태 하나\n[VISUAL TRANSLATION]\nCreative DNA를 글로 나열하지 말고 의상, 소재, 공간, 빛, 상징물, 배경, 색, 캐릭터의 자세와 시선 등으로 변환합니다.\n사용자의 실제 관심사를 상징하는 오브제는 2~3개만 선택합니다.\n[VISUAL STYLE]\nConceptual Fine-Art Artist Portrait\n세계적인 아트·패션 매거진에서 한 명의 창작자를 소개하는 컨셉추얼 포트레이트처럼 표현합니다.\nfine-art photography, editorial portrait, subtle surrealism, cinematic lighting, artistic symbolism을 결합합니다.\n다꾸, 스크랩북, 찢어진 종이, 메모지, 마스킹테이프, 정보 박스, 귀여운 양모펠트 캐릭터는 사용하지 않습니다.\n인물이 자신의 작품 세계 안에 실제로 들어가 있는 것처럼 표현합니다.\n현실과 상상이 자연스럽게 섞이는 절제된 초현실주의를 활용합니다.\n단순히 예쁜 인물이 아니라 한눈에 “이 사람은 어떤 세계를 만드는 작가일까?”라는 궁금증이 생기는 비주얼이어야 합니다.\n[IMAGE TEXT]\n나의 AI 작가 캐릭터는?\n[ARTIST NAME]\n[CREATIVE TYPE]\nDNA 1 · DNA 2 · DNA 3\n그 외 설명은 넣지 않습니다.\n핵심: 프로필 사진이 아니라 한 사람의 창작 세계를 한 장의 작가 초상으로 만들어 주세요.",
    "tip": "충분한 대화 기록이 있는 채팅에서 사용해야 결과가 더 구체적이며, 확인되지 않은 성향은 추측하지 않도록 합니다.",
    "variation": "타입 / 창작 컬러 / 동물 / 마음의 정원 / 작가 캐릭터",
    "source": "AI SELF-DISCOVERY ART 01–05"
  },
  {
    "id": "p52",
    "category": "이미지 확장",
    "icon": "↗",
    "title": "작품 너머의 세계 · 초기 완성형",
    "level": "고급",
    "ratio": "원본에 맞춤",
    "tool": "ChatGPT Image",
    "summary": "업로드한 원본의 시각적 DNA를 분석하고 예상하지 못한 다음 장면으로 확장합니다.",
    "when": "완성된 이미지의 단순 변형이 아니라, 원본이 품고 있던 새로운 가능성을 발견하고 싶을 때 사용합니다.",
    "prompt": "지금 업로드한 이미지를 자세히 살펴보고,\n“이 작품에서 지금 보이는 장면 너머에는\n어떤 세계가 존재할까?”\n를 상상해 주세요.\n단순히 원본 이미지를 확대하거나\n비슷한 그림을 한 장 더 만드는 것이 아닙니다.\n원본 이미지에서 보이는\n색, 빛, 질감, 형태, 공간감, 분위기, 감정,\n상징적인 요소와 시선의 흐름을 분석한 뒤,\n원본의 정체성은 느껴지지만\n아직 한 번도 보지 못했던 새로운 장면으로 확장해 주세요.\nSTEP 1. 작품 읽기\n먼저 업로드한 이미지에서 다음 요소를 내부적으로 분석합니다.\n- 가장 중심이 되는 색과 빛\n- 작품에서 느껴지는 정서\n- 반복되는 형태와 질감\n- 시선을 끄는 핵심 요소\n- 작품이 암시하지만 아직 보여주지 않은 것\n분석 내용은 길게 설명하지 않습니다.\n그 분석을 새로운 장면을 만드는 근거로만 사용합니다.\nSTEP 2. 작품 너머 상상하기\n원본 작품이 하나의 세계로 이어져 있다고 상상합니다.\n그리고 지금 화면에는 보이지 않았던\n‘그 너머의 장면’을 새롭게 만들어 주세요.\n중요합니다.\n원본과 똑같은 구도나 풍경을 반복하지 마세요.\n단순히 카메라를 조금 이동하거나\n배경을 넓히는 수준으로 만들지 마세요.\n원본의 색과 분위기를 그대로 복제하는 것보다,\n그 작품이 가진 감성과 시각적 DNA가\n새로운 공간, 물성, 빛, 사건, 오브제 또는 세계로\n변화하도록 해주세요.\n예측 가능한 판타지 성, 궁전, 꽃밭, 우주,\n포털 등을 습관적으로 추가하지 마세요.\n업로드된 작품을 먼저 읽고\n그 작품에서만 나올 수 있는 장면을 선택합니다.\n필요하다면 원본에 없던 새로운 요소가 등장해도 좋습니다.\n다만 새로운 요소에도\n원본 작품의 색과 감정적 연결성이 느껴져야 합니다.\nSTEP 3. 한 문장 발견하기\n새로운 장면을 완성한 뒤\n그 장면을 위한 짧은 문장 하나를 만듭니다.\n미리 정해진 문장을 사용하지 마세요.\n원본 작품과 새롭게 만들어진 장면을 함께 해석해서\n이 작품에서만 나올 수 있는 문장을 작성합니다.\n문장은 설명문이 아니라\n작품의 여운을 남기는 짧고 시적인 한국어 문장이어야 합니다.\n사람마다, 작품마다 다른 문장이 나오도록 합니다.\n예:\n“고요했던 빛이, 마침내 길이 되었습니다.”\n위 문장은 형식의 예일 뿐이며\n그대로 반복해서 사용하지 않습니다.\nSTEP 4. 이미지 제작\n최종 결과는 한 장의 완성된 아트 작품으로 제작합니다.\n원본의 시각적 DNA는 느껴지되\n원본과 비교했을 때 분명한 변화와 발견이 있어야 합니다.\n보는 사람이\n“비슷한 그림을 하나 더 만들었네.”\n가 아니라\n“이 이미지에서 이런 세계가 나왔다고?”\n라는 느낌을 받을 수 있도록 해주세요.\n원본에 사람이 있는 경우,\n새로운 장면에 그 사람이 반드시 다시 등장할 필요는 없습니다.\n원본이 추상 작품이라면\n또 다른 추상 작품으로만 반복하지 말고\n필요하면 공간, 오브제, 자연현상, 건축적 형태 등\n전혀 다른 시각적 언어로 변환할 수 있습니다.\nTEXT\n이미지에는 AI가 이번 작품을 위해 만든\n짧은 문장 하나만 넣어주세요.\n필요하다면 그 아래 아주 작게\nBEYOND THE IMAGE\n를 넣습니다.\n그 외 제목, 설명문, 분석 결과,\n정보 카드, 컬러칩 등은 넣지 않습니다.\n한글은 정확하게 표현합니다.\n가장 중요한 원칙\n원본을 복제하지 말고,\n원본이 품고 있던 가능성을 발견하세요.\n비슷하게 만들기보다 연결되게 만들고,\n예쁘게 꾸미기보다 예상하지 못한 장면을 보여주세요.\n분석을 마쳤다면\n추가 질문이나 설명 없이 바로 이미지를 제작해 주세요.",
    "tip": "원본의 색·빛·질감·형태 가운데 2~3개만 연결 단서로 남기고, 단순 확대나 배경 확장은 피하세요.",
    "variation": "시간 변화 / 화면 밖 공간 / 빛의 물질화 / 배경의 주인공화",
    "source": "BEYOND THE IMAGE"
  },
  {
    "id": "p53",
    "category": "이미지 확장",
    "icon": "↗",
    "title": "아직 보지 못한 것 · 확장 프롬프트",
    "level": "고급",
    "ratio": "원본에 맞춤",
    "tool": "ChatGPT Image",
    "summary": "업로드한 원본의 시각적 DNA를 분석하고 예상하지 못한 다음 장면으로 확장합니다.",
    "when": "완성된 이미지의 단순 변형이 아니라, 원본이 품고 있던 새로운 가능성을 발견하고 싶을 때 사용합니다.",
    "prompt": "지금 업로드한 이미지 한 장을 자세히 바라봐 주세요.\n그리고 이 질문에서 시작합니다.\n“이 작품에서 내가 아직 보지 못한 것은 무엇일까?”\n원본과 비슷한 이미지를 한 장 더 만드는 것이 아닙니다.\n이미지 속에 이미 존재하지만 아직 명확하게 드러나지 않은\n감정, 움직임, 관계, 시간, 공간, 상징, 이야기의 가능성 중\n가장 흥미로운 하나를 발견하여 새로운 한 장의 작품으로 보여주세요.\n1. 먼저 작품을 읽어주세요\n업로드된 이미지에서 내부적으로 다음을 살펴봅니다.\n• 가장 먼저 시선을 끄는 요소\n• 중심이 되는 색과 빛\n• 독특한 형태와 질감\n• 화면의 흐름과 방향\n• 작품이 주는 감정\n• 정지된 화면 안에서 느껴지는 움직임\n• 이미 일어난 것처럼 보이는 일\n• 앞으로 일어날 것처럼 느껴지는 일\n• 화면 밖에 존재할 것 같은 것\n• 작품에서 설명되지 않은 가장 흥미로운 단서\n단순히 사물과 색을 나열하지 마세요.\n이 작품만의 특징이 무엇인지 충분히 이해한 뒤\n다음 단계로 넘어갑니다.\n2. 하나의 가능성을 발견해주세요\n분석한 내용을 바탕으로\n“이 작품이 아직 보여주지 않은 가장 흥미로운 것은 무엇인가?”\n를 판단합니다.\n매번 같은 방식으로 확장하지 마세요.\n작품에 따라 다음과 같이 전혀 다른 변화가 일어날 수 있습니다.\n• 시간이 흐른 뒤의 모습\n• 화면 밖에 있던 공간의 등장\n• 정지되어 있던 무언가의 움직임\n• 빛이나 색이 실제 물질로 변화\n• 작은 요소가 거대한 세계로 확장\n• 배경에 있던 것이 주인공이 됨\n• 보이지 않던 존재의 흔적이 나타남\n• 계절이나 시간의 변화\n• 공간의 성격이 완전히 달라짐\n• 추상적인 형태가 실제 공간이나 오브제로 변화\n• 원본 속 상징이 예상하지 못한 형태로 발전\n위 예시는 가능성일 뿐입니다.\n반드시 이 중 하나를 선택할 필요는 없습니다.\n가장 중요한 것은\n“이 이미지라서 가능한 변화”\n를 찾는 것입니다.\n3. 예상 가능한 확장은 피해주세요\n원본의 색을 그대로 사용해\n비슷한 풍경을 하나 더 만들지 마세요.\n단순 확대,\n카메라 이동,\n배경 확장,\n색상 복제만으로 끝내지 마세요.\n또한 작품에 근거가 없는데도 습관적으로\n판타지 성,\n궁전,\n거대한 문,\n포털,\n우주,\n꽃밭,\n폭포,\n천사,\n날개,\n크리스털 도시\n등을 추가하지 않습니다.\n그 요소가 원본 작품을 분석했을 때\n가장 자연스럽고 의미 있는 선택일 경우에만 사용합니다.\n4. 원본과 연결되는 단서는 남겨주세요\n새로운 작품은 원본과 분명히 달라야 하지만\n두 이미지를 나란히 놓았을 때\n“완전히 다른 작품인데,\n분명 저 이미지에서 태어났구나.”\n라는 느낌이 있어야 합니다.\n이를 위해 원본에서 가장 중요한\n색, 빛, 질감, 형태, 오브제, 분위기 중\n2~3개의 시각적 DNA를 선택하여 새로운 장면에 자연스럽게 남깁니다.\n모든 요소를 그대로 가져오지는 않습니다.\n5. 작품마다 다른 문장을 만들어주세요\n새로운 장면을 만든 뒤\n원본과 새로운 작품 사이의 변화를 표현하는\n짧은 문장 하나를 만듭니다.\n문장은 미리 정하지 않습니다.\n이미지를 분석한 결과에 따라\n매번 완전히 다르게 작성합니다.\n설명문보다는 작품을 보고 난 뒤\n잠시 생각하게 만드는 문장을 만들어주세요.\n너무 추상적이거나 상투적인 표현은 피합니다.\n특히\n“새로운 세계가 열렸습니다.”\n“이야기가 시작되었습니다.”\n“빛이 길이 되었습니다.”\n같은 문장을 반복적으로 사용하지 않습니다.\n문장은 가능하면 1~2줄,\n짧고 자연스러운 한국어로 작성합니다.\n6. 최종 이미지를 제작해주세요\n이제 분석 결과를 설명하지 말고\n바로 새로운 작품 한 장을 제작합니다.\n원본의 복제본이 아니라\n원본에서 발견한 가능성을 시각화한 작품이어야 합니다.\n사람이 없는 작품에\n억지로 사람을 등장시키지 마세요.\n반대로 인물이 있는 작품이라고 해서\n반드시 같은 인물을 다시 등장시킬 필요도 없습니다.\n추상 작품은 또 다른 추상 작품으로만 만들지 않아도 됩니다.\n사진 역시 사진 스타일을 반드시 유지할 필요는 없습니다.\n작품의 의미를 더 잘 표현할 수 있다면\n공간, 오브제, 자연현상, 설치미술,\n초현실적 장면, 시네마틱 장면 등으로\n자유롭게 변화시킬 수 있습니다.\nIMAGE TEXT\n이미지에는 이번 작품을 위해 만든\n짧은 문장 하나만 넣습니다.\n필요하다면 아주 작게\nBEYOND THE IMAGE\n를 넣어도 됩니다.\n분석 내용,\n긴 설명,\n정보 카드,\n컬러칩,\n여러 개의 텍스트 박스는 넣지 않습니다.\n한글은 정확하게 표현합니다.\nFINAL RULE\n예쁘게 이어가는 것보다\n예상하지 못한 것을 발견하는 것이 중요합니다.\n원본을 반복하지 말고,\n원본이 품고 있던 가능성을 보여주세요.\n같은 사람이 같은 프롬프트를 여러 번 사용해도\n매번 똑같은 확장 방식이 나오지 않도록 합니다.\n분석이 끝났다면\n사용자에게 추가 질문하거나 분석 내용을 설명하지 말고\n바로 이미지를 제작해주세요.",
    "tip": "원본의 색·빛·질감·형태 가운데 2~3개만 연결 단서로 남기고, 단순 확대나 배경 확장은 피하세요.",
    "variation": "시간 변화 / 화면 밖 공간 / 빛의 물질화 / 배경의 주인공화",
    "source": "BEYOND THE IMAGE"
  },
  {
    "id": "p54",
    "category": "이미지 확장",
    "icon": "↗",
    "title": "BEYOND THE IMAGE · 최종 정리",
    "level": "고급",
    "ratio": "원본에 맞춤",
    "tool": "ChatGPT Image",
    "summary": "업로드한 원본의 시각적 DNA를 분석하고 예상하지 못한 다음 장면으로 확장합니다.",
    "when": "완성된 이미지의 단순 변형이 아니라, 원본이 품고 있던 새로운 가능성을 발견하고 싶을 때 사용합니다.",
    "prompt": "지금 업로드한 이미지 한 장을 자세히 바라봐 주세요.\n그리고 이 질문에서 시작합니다.\n“이 작품에서 내가 아직 보지 못한 것은 무엇일까?”\n원본과 비슷한 이미지를 한 장 더 만드는 것이 아닙니다.\n이미지 속에 이미 존재하지만 아직 명확하게 드러나지 않은\n감정, 움직임, 관계, 시간, 공간, 상징, 이야기의 가능성 중\n가장 흥미로운 하나를 발견하여\n새로운 한 장의 작품으로 보여주세요.\nSTEP 1. 작품 읽기\n먼저 업로드한 이미지에서 내부적으로 분석합니다.\n- 가장 먼저 시선을 끄는 요소\n- 중심이 되는 색과 빛\n- 독특한 형태와 질감\n- 화면의 흐름과 방향\n- 작품에서 느껴지는 감정\n- 정지된 화면 안에서 느껴지는 움직임\n- 화면 밖에 존재할 것 같은 것\n- 작품에서 아직 설명되지 않은 흥미로운 단서\n분석 결과를 길게 설명하지 말고\n새로운 작품을 만드는 근거로 사용합니다.\nSTEP 2. 아직 보지 못한 것 발견하기\n분석을 바탕으로\n“이 작품이 아직 보여주지 않은\n가장 흥미로운 가능성은 무엇인가?”\n를 판단합니다.\n시간이 흐를 수도 있고,\n화면 밖의 공간이 나타날 수도 있고,\n색이나 빛이 실제 물질이 될 수도 있고,\n작은 요소가 거대한 세계가 될 수도 있고,\n배경이 주인공이 될 수도 있으며,\n추상적인 형태가 공간이나 오브제로 변할 수도 있습니다.\n하지만 위의 예를 그대로 반복하지 마세요.\n항상\n“이 이미지라서 가능한 변화”\n를 찾아주세요.\nSTEP 3. 뻔한 확장 피하기\n단순 확대,\n카메라 이동,\n배경 확장,\n비슷한 풍경 생성,\n색상만 유지한 반복 이미지는 피합니다.\n작품에 근거가 없는데도 습관적으로\n판타지 성, 궁전, 포털, 우주,\n꽃밭, 폭포, 날개, 크리스털 도시\n등을 추가하지 않습니다.\n원본 작품을 분석했을 때\n필요한 경우에만 사용합니다.\nSTEP 4. 원본의 흔적 남기기\n새로운 작품은 원본과 분명히 달라야 합니다.\n하지만 두 작품을 나란히 놓았을 때\n“완전히 새로운 작품인데\n분명 이 이미지에서 태어났구나.”\n라는 느낌이 있어야 합니다.\n원본에서 가장 중요한\n색, 빛, 질감, 형태, 오브제, 분위기 중\n2~3개의 시각적 DNA만 선택해\n새로운 작품에 자연스럽게 연결합니다.\nSTEP 5. 작품만의 한 문장\n원본과 새롭게 만들어진 작품의 관계를 읽고\n이 작품에서만 나올 수 있는\n짧은 한국어 문장 하나를 창작합니다.\n미리 정해진 문장을 사용하지 않습니다.\n사람마다,\n이미지마다,\n결과마다 다른 문장이 나와야 합니다.\n설명보다는 여운을 남기는\n짧고 자연스러운 문장으로 표현합니다.\n상투적인 문구를 반복하지 않습니다.\nSTEP 6. 이미지 제작\n분석이 끝났다면 설명하지 말고\n바로 새로운 작품 한 장을 제작합니다.\n원본의 복제본이 아니라\n원본에서 발견한 가능성을 시각화합니다.\n원본과의 연결은 느껴지되\n결과의 장면, 공간, 사건 또는 표현 방식에는\n분명한 변화가 있어야 합니다.\n보는 사람이\n“비슷한 그림이네.”\n보다\n“이 이미지에서 이게 나왔다고?”\n라고 느낄 수 있게 해주세요.\nIMAGE TEXT\n이미지에는 이번 작품을 위해 새롭게 만든\n짧은 문장 하나만 넣습니다.\n필요한 경우 아래에 아주 작게\nBEYOND THE IMAGE\n를 넣습니다.\n분석 내용, 설명문, 컬러칩,\n정보 카드, 여러 개의 텍스트 박스는 넣지 않습니다.\n한글은 정확하게 표현합니다.\nFINAL RULE\n원본을 복제하지 말고\n원본이 품고 있던 가능성을 발견하세요.\n예쁘게 이어가는 것보다\n예상하지 못한 것을 발견하는 것이 중요합니다.\n같은 프롬프트를 여러 사람이 사용해도\n각자의 이미지에서 전혀 다른 발견이 일어나도록 합니다.\n분석을 마쳤다면\n추가 질문이나 설명 없이\n바로 이미지를 제작해주세요.",
    "tip": "원본의 색·빛·질감·형태 가운데 2~3개만 연결 단서로 남기고, 단순 확대나 배경 확장은 피하세요.",
    "variation": "시간 변화 / 화면 밖 공간 / 빛의 물질화 / 배경의 주인공화",
    "source": "BEYOND THE IMAGE"
  },
  {
    "id": "p55",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "별이 빛나는 밤 , 성산일출봉",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "빈센트 반 고흐의 ' 별이 빛나는 밤 ' 스타일로 , 소용돌이치는 밤하늘과 성산 일출봉의 실루엣을 AI 가 몽환적으로 표현 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p56",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "제주 해녀의 초상",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "얀 베르메르의 ' 진주 귀걸이를 한 소녀 ' 처럼 , 해녀의 강인함과 신비로움을 담아 AI 가 섬세한 빛과 그림자로 재해석 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p57",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "서핑하는 비너스 , 협재 해변",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "산드로 보티첼리의 ' 비너스의 탄생 ' 을 현대적으로 재해석하여 , 협재 해변의 에메랄드빛 바다 위로 서핑 보드를 탄 비너스를 AI 가 유쾌하게 그려냄 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p58",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "월정리 해변의 만찬",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "레오나르도 다 빈치의 ' 최후의 만찬 ' 구도에 , 제주 전통 음식을 나누는 사람들을 배 치하고 , 배경으로 월정리 해변의 풍경을 AI 가 사실적으로 묘사 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p59",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "봄날 , 동백꽃 숲 속의 여인",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "클로드 모네의 인상주의 기법으로 , 제주의 동백꽃 숲을 배경으로 AI 가 빛의 효과를 극대화하여 따뜻하고 화사한 분위기의 여성 초상화 제작 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p60",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "오름 위 붉은 노을",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "카라바조의 극적인 명암 대비 ( 키아로스쿠로 ) 기법을 활용하여 , 제주의 오름 위로 지 는 붉은 노을의 강렬한 빛과 그림자를 AI 가 드라마틱하게 표현 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p61",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "사려니 숲길의 신비로운 동반자",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "르네 마그리트의 초현실주의 스타일로 , 사려니 숲길에 갑자기 나타난 AI 생성 동물 ( 예 : 날개 달린 말 , 빛나는 사슴 ) 을 그려 신비롭고 낯선 느낌 연출 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p62",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "한라산 설경 , 고요한 명상",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "잭슨 폴록의 액션 페인팅 기법을 추상화하여 , 한라산의 눈 덮인 풍경을 AI 가 역동적인 물감의 흐름과 질감으로 표현 . ( 고요함 속에 내재된 에너지 )",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p63",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "바람 부는 제주 , 움직이는 풍경",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "에드가 드가의 발레리나 그림처럼 , 제주의 바람에 흩날리는 유채꽃밭이 나 해초를 AI 가 움직임의 순간을 포착하여 경쾌하게 표현 .",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  },
  {
    "id": "p64",
    "category": "명화 재해석",
    "icon": "▣",
    "title": "미래의 제주 , AI 건축가",
    "level": "중급",
    "ratio": "4:5",
    "tool": "ChatGPT Image · Midjourney",
    "summary": "유명 명화의 구도와 기법을 제주 자연·문화 요소로 재구성하는 시리즈 아이디어입니다.",
    "when": "명화의 시각적 특징을 제주 지역성과 결합한 전시·수업 작품을 기획할 때 사용합니다.",
    "prompt": "파블로 피카소의 입체주의 스타일을 적용하여 , 제주의 자연 ( 돌 , 바람 , 바다 ) 을 해체하고 재조합한 독창적인 AI 건축 디자인을 선보임 . ( 건축 디자인 컨셉 아트 )",
    "tip": "원작을 그대로 복제하기보다 구도·색감·기법 중 핵심 한 가지를 제주 요소와 연결하세요.",
    "variation": "제주 장소 / 시간대 / 계절 / 표현 기법",
    "source": "명화 재해석"
  }
];
